services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    env_file: api/.env
    restart: on-failure
    entrypoint: ["./entrypoint.sh"]
    command: yarn start:dev
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DATABASE=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: